services:
  - type: web
    name: ai-fashion-stylist-api
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
